# Generated by Django 5.1.6 on 2025-04-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
