# Generated by Django 5.1.6 on 2025-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='head_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
