# Generated by Django 5.1.6 on 2025-04-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioitem_head_title_portfolioitem_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image3',
        ),
    ]
