# Generated by Django 5.1.6 on 2025-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolioitem_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(help_text='esas sekil ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image1',
            field=models.ImageField(help_text='453x499, Sekil olculeri mutleq verilmis olcude olmalidir. ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image2',
            field=models.ImageField(help_text='572x421, Sekil olculeri mutleq verilmis olcude olmalidir. ', null=True, upload_to=''),
        ),
    ]
