# Generated by Django 5.1.6 on 2025-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioitem_image_alter_portfolioitem_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='content2',
            field=models.TextField(default='test', help_text='Is haqqinda melumat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='content',
            field=models.TextField(help_text='Is haqqinda melumat'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='subject',
            field=models.CharField(help_text='hansi is oldugunu qeyd etmek', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='tittle',
            field=models.CharField(help_text='Işin adı', max_length=100),
        ),
    ]
