# Generated by Django 5.1.6 on 2025-04-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_portfolioitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content2',
            field=models.TextField(blank=True, help_text='Is haqqinda melumat', null=True),
        ),
    ]
