# Generated by Django 5.1.6 on 2025-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_portfolioitem_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content2',
            field=models.TextField(blank=True, help_text='İş haqqında məlumat', null=True),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(help_text='Əsas şəkil, Şəkil ölçüləri mütləq verilmiş ölçüdə olmalıdır 1300x750 ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image1',
            field=models.ImageField(help_text='453x499, Şəkil ölçüləri mütləq verilmiş ölçüdə olmalıdır. ', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image2',
            field=models.ImageField(help_text='572x421, Şəkil ölçüləri mütləq verilmiş ölçüdə olmalıdır. ', null=True, upload_to=''),
        ),
    ]
