# Generated by Django 5.1.6 on 2025-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_portfolioitem_content2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='content',
            field=models.TextField(help_text='İş haqqında məlumat'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='subject',
            field=models.CharField(help_text='Hansı iş olduğunu qeyd etmək', max_length=100),
        ),
    ]
